<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

<ItemGroup>
	<Folder Include="Domain\" />
	<Folder Include="Features\" />
</ItemGroup>

<ItemGroup>
  <ProjectReference Include="..\Authentication.Contracts\Authentication.Contracts.csproj" />
</ItemGroup>

<ItemGroup>
  <PackageReference Include="FastApi" Version="1.0.71" />
  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
  <PackageReference Include="MongoDB.Bson" Version="3.8.1" />
  <PackageReference Include="MongoDB.Driver" Version="3.8.1" />
  <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.0.0" />
</ItemGroup>

</Project>
